module Emit {
  private use List;
  private use Map;
  private use Sort;
  private use Path;
  private use FileSystem;
  private use Diagnostics;
  private use Manifest;
  private use AppConfig;
  private use Assets;
  private use Text only chplLiteral;

  param BANNER = "// Generated by cataract-cli. Do not edit; run `cataract build`.\n\n";

  record Emitted {
    var generatedDir: string;
    var mainModule: string = "CataractMain";
    var files: list(string);
    var rewritten: int = 0;
  }

  proc emit(const ref cfg: ProjectConfig, root: string, const ref bundle: Bundle,
            const ref assets: AssetTable, ref diags: Bag): Emitted throws {
    var result = new Emitted();
    result.generatedDir = joinPath(resolveIn(root, cfg.outDir), "generated");
    ensureDir(result.generatedDir, diags);

    emitFile(result, "CataractAssets.chpl", assetsModule(assets), diags);
    emitFile(result, "GeneratedRoutes.chpl", routesModule(bundle, assets), diags);
    emitFile(result, "CataractMain.chpl", mainModuleSource(cfg, root), diags);
    pruneStale(result, diags);

    return result;
  }

  private proc pruneStale(const ref result: Emitted, ref diags: Bag) throws {
    for entry in listDir(result.generatedDir, hidden = false) {
      const path = joinPath(result.generatedDir, entry);
      var wanted = false;
      for f in result.files do if f == path then wanted = true;
      if wanted then continue;
      try {
        remove(path);
      } catch e {
        diags.note(path, "stale generated file could not be removed: " + e.message());
      }
    }
  }

  private proc emitFile(ref result: Emitted, name: string, content: string,
                        ref diags: Bag) throws {
    const path = joinPath(result.generatedDir, name);
    if writeIfChanged(path, content, diags) then result.rewritten += 1;
    result.files.pushBack(path);
  }

  private proc assetsModule(const ref assets: AssetTable): string throws {
    var sb = BANNER;
    sb += "module CataractAssets {\n";
    /* A select, so asset lookup compiles to a jump table, not a runtime map. */
    sb += "  proc asset(path: string): string {\n";

    var keys: list(string);
    for k in assets.digests.keys() do keys.pushBack(k);
    var sorted = keys.toArray();
    sort(sorted);

    if sorted.size == 0 {
      sb += "    return path;\n";
    } else {
      sb += "    select path {\n";
      for k in sorted do
        sb += "      when " + chplLiteral(k) + " do return " +
               chplLiteral(k + "?v=" + assets.digests[k]) + ";\n";
      sb += "      otherwise do return path;\n";
      sb += "    }\n";
    }
    sb += "  }\n";
    sb += "}\n";
    return sb;
  }

  private proc routesModule(const ref bundle: Bundle,
                            const ref assets: AssetTable): string throws {
    var sb = BANNER;
    sb += "module GeneratedRoutes {\n";
    sb += "  use Cataract;\n";
    sb += "  use CataractAssets;\n";
    for m in bundle.pageModules do sb += "  use " + m + ";\n";
    for m in bundle.apiModules do sb += "  use " + m + ";\n";
    for l in sortedLayoutNames(bundle) do
      sb += "  use " + bundle.layouts[l].moduleName + ";\n";
    sb += "\n";

    var sheets: list(string);
    for k in assets.digests.keys() do
      if k.endsWith(".css") && countSlashes(k) == 1 then sheets.pushBack(k);
    var sortedSheets = sheets.toArray();
    sort(sortedSheets);

    for r in bundle.routes {
      sb += handlerClass(r, bundle, sortedSheets);
      sb += "\n";
    }

    sb += "  proc registerRoutes(app: borrowed App) throws {\n";
    for r in bundle.routes {
      sb += "    app.route(" + chplLiteral(r.pattern) + ", " +
             methodMaskExpr(r.methods) + ", RouteKind." + kindConstant(r.kind) + ", " +
             chplLiteral(r.sourcePath) + ", new shared " + handlerName(r) + "());\n";
    }
    sb += "  }\n";
    sb += "}\n";
    return sb;
  }

  private proc sortedLayoutNames(const ref bundle: Bundle): [] string throws {
    var names: list(string);
    for n in bundle.layouts.keys() do names.pushBack(n);
    var arr = names.toArray();
    sort(arr);
    return arr;
  }

  private proc countSlashes(s: string): int throws {
    var n = 0;
    for i in 0..<s.numBytes do if s.byte(i) == 47 then n += 1;
    return n;
  }

  proc kindConstant(kind: EntryKind): string throws {
    select kind {
      when EntryKind.page do return "page";
      when EntryKind.socket do return "socket";
      otherwise do return "api";
    }
  }

  private proc handlerName(const ref r: RouteEntry): string throws {
    return "H__" + r.symbol;
  }

  private proc handlerClass(const ref r: RouteEntry, const ref bundle: Bundle,
                            const ref sheets: [] string): string throws {
    var sb = "  class " + handlerName(r) + ": Handler {\n";

    if r.kind == EntryKind.socket {
      sb += socketBody(r);
      sb += "  }\n";
      return sb;
    }

    sb += "    override proc handle(ctx: Context): Response {\n";

    if r.kind == EntryKind.page {
      const layout = bundle.layouts[r.layout];
      sb += "      var __meta = new PageMeta();\n";
      for s in sheets do
        sb += "      __meta.stylesheets.pushBack(asset(" + chplLiteral(s) + "));\n";

      const guarded = r.throwsRender || layout.throwsRender;
      const pad = if guarded then "        " else "      ";
      if guarded then sb += "      try {\n";
      sb += pad + "const __body = " + r.moduleName + ".page(ctx, __meta);\n";
      sb += pad + "const __page = " + layout.moduleName +
             ".layout(ctx, __body, __meta);\n";
      sb += pad + "return htmlResponse(renderDocument(__meta, __page), __meta.status);\n";
      if guarded {
        sb += "      } catch e {\n";
        sb += "        logError(" + chplLiteral(r.pattern) +
               " + \" render failed: \" + e.message());\n";
        sb += "        return errorResponse(500);\n";
        sb += "      }\n";
      }
    } else {
      sb += "      select effectiveMethod(ctx.request.method) {\n";
      for m in r.methods {
        const call = r.moduleName + "." + enumConstant(m) + "(ctx)";
        sb += "        when Method." + enumConstant(m) + " {\n";
        if listContains(r.throwsMethods, m) {
          sb += "          try {\n";
          sb += "            return " + call + ";\n";
          sb += "          } catch e {\n";
          sb += "            logError(" + chplLiteral(r.pattern + " " + m) +
                 " + \" failed: \" + e.message());\n";
          sb += "            return errorResponse(500);\n";
          sb += "          }\n";
        } else {
          sb += "          return " + call + ";\n";
        }
        sb += "        }\n";
      }
      sb += "        otherwise do return errorResponse(405);\n";
      sb += "      }\n";
      sb += "      return errorResponse(405);\n";
    }

    sb += "    }\n";
    sb += "  }\n";
    return sb;
  }

  private proc socketBody(const ref r: RouteEntry): string throws {
    var sb = "    override proc handle(ctx: Context): Response {\n";
    sb += "      var res = errorResponse(426, \"this route speaks WebSocket\");\n";
    sb += "      res.setHeader(\"Upgrade\", \"websocket\");\n";
    sb += "      res.setHeader(\"Connection\", \"Upgrade\");\n";
    sb += "      return res;\n";
    sb += "    }\n\n";

    sb += "    override proc serveSocket(ctx: Context, socket: shared WebSocket) {\n";
    if r.throwsRender {
      sb += "      try {\n";
      sb += "        " + r.moduleName + ".socket(ctx, socket);\n";
      sb += "      } catch e {\n";
      sb += "        logError(" + chplLiteral(r.pattern) +
             " + \" socket failed: \" + e.message());\n";
      sb += "        socket.closeWith(CLOSE_GOING_AWAY, \"handler failed\");\n";
      sb += "      }\n";
    } else {
      sb += "      " + r.moduleName + ".socket(ctx, socket);\n";
    }
    sb += "    }\n";
    return sb;
  }

  /* `delete` is a Chapel keyword; enum constant and handler both spell it `del`. */
  proc enumConstant(httpMethod: string): string throws {
    const lower = httpMethod.toLower();
    return if lower == "delete" then "del" else lower;
  }

  private proc listContains(const ref l: list(string), v: string): bool throws {
    for x in l do if x == v then return true;
    return false;
  }

  private proc mainModuleSource(const ref cfg: ProjectConfig, root: string): string throws {
    const publicOut = joinPath(resolveIn(root, cfg.outDir), "public");

    var sb = BANNER;
    sb += "module CataractMain {\n";
    sb += "  use Cataract;\n";
    sb += "  use GeneratedRoutes;\n";
    sb += "  use AccessLog;\n";
    sb += "  use SecurityHeaders;\n";
    sb += "  use StaticFiles;\n\n";

    sb += "  config const host = " + chplLiteral(cfg.host) + ";\n";
    sb += "  config const port = " + cfg.port:string + ";\n";
    sb += "  config const maxConcurrency = " + cfg.maxConcurrency:string + ";\n";
    sb += "  config const maxBodyBytes = " + cfg.maxBodyBytes:string + ";\n";
    sb += "  config const keepAliveMillis = " + cfg.keepAliveTimeoutMillis:string + ";\n";
    sb += "  config const headerTimeoutMillis = " + cfg.headerTimeoutMillis:string + ";\n";
    sb += "  config const requestTimeoutMillis = " + cfg.requestTimeoutMillis:string + ";\n";
    sb += "  config const logLevel = " + chplLiteral(cfg.logLevel) + ";\n";
    sb += "  config const socketMaxMessageBytes = " +
           cfg.socketMaxMessageBytes:string + ";\n";
    sb += "  config const socketIdleTimeoutMillis = " +
           cfg.socketIdleTimeoutMillis:string + ";\n";
    sb += "  config const socketSendTimeoutMillis = " +
           cfg.socketSendTimeoutMillis:string + ";\n";
    sb += "  config const socketSubprotocols = " +
           chplLiteral(cfg.socketSubprotocols) + ";\n";
    sb += "  config const staticRoot = " + chplLiteral(publicOut) + ";\n";
    sb += "  config const devMode = false;\n";
    sb += "  config const hstsSeconds = " + cfg.hstsSeconds:string + ";\n";
    sb += "  config const allowedOrigins = " + chplLiteral(cfg.allowedOrigins) + ";\n\n";

    sb += "  proc main(args: [] string): int {\n";
    sb += "    setLevel(parseLevel(logLevel));\n\n";
    sb += "    var serverConfig = new ServerConfig();\n";
    sb += "    serverConfig.host = host;\n";
    sb += "    serverConfig.port = port;\n";
    sb += "    serverConfig.maxConcurrency = maxConcurrency;\n";
    sb += "    serverConfig.keepAliveTimeoutMillis = keepAliveMillis;\n";
    sb += "    serverConfig.headerTimeoutMillis = headerTimeoutMillis;\n";
    sb += "    serverConfig.devMode = devMode;\n";
    sb += "    serverConfig.socketMaxMessageBytes = socketMaxMessageBytes;\n";
    sb += "    serverConfig.socketIdleTimeoutMillis = socketIdleTimeoutMillis;\n";
    sb += "    serverConfig.socketSendTimeoutMillis = socketSendTimeoutMillis;\n";
    sb += "    serverConfig.socketSubprotocols = socketSubprotocols;\n";
    sb += "    serverConfig.limits.maxBodyBytes = maxBodyBytes;\n";
    sb += "    serverConfig.limits.requestTimeoutMillis = requestTimeoutMillis;\n\n";

    sb += "    var app = new owned App(serverConfig);\n\n";
    sb += "    // Entry order is unwind order reversed: the logger wraps everything.\n";
    sb += "    app.addMiddleware(new shared AccessLogger());\n";

    sb += "    var guard = new shared SecurityGuard();\n";
    if !cfg.contentSecurityPolicy.isEmpty() then
      sb += "    guard.contentSecurityPolicy = " +
             chplLiteral(cfg.contentSecurityPolicy) + ";\n";
    sb += "    guard.hstsSeconds = hstsSeconds;\n";
    sb += "    guard.allowedOrigins = allowedOrigins;\n";
    sb += "    app.addMiddleware(guard);\n\n";

    sb += "    var files = new shared StaticFileServer(staticRoot, !devMode);\n";
    sb += "    app.addMiddleware(files);\n\n";

    sb += "    try {\n";
    sb += "      registerRoutes(app.borrow());\n";
    sb += "      app.listenAndServe();\n";
    sb += "    } catch e {\n";
    sb += "      logError(e.message());\n";
    sb += "      return 1;\n";
    sb += "    }\n";
    sb += "    return 0;\n";
    sb += "  }\n";
    sb += "}\n";
    return sb;
  }
}
